export type CanonType="vessel"|"system"|"person"|"celestial_body"|"technology"|"mission"|"science"|"era"|"book";
export type Visibility="public"|"future_public"|"private_canon"|"plot_locked"|"draft"|"deprecated";
export type CanonStatus="confirmed"|"provisional"|"conflicted";
export type CanonRecord={id:string;slug:string;title:string;type:CanonType;summary:string;description?:string;status:Visibility;canonStatus:CanonStatus;tags:string[];metadata?:Record<string,string|number>;relationships?:{targetId:string;type:string}[];sources?:{sourceId:string;reference:string;confidence:CanonStatus}[];lastReviewed:string};

export const canonRecords:CanonRecord[]=[
 {id:"lumen",slug:"lumen",title:"Lumen",type:"vessel",summary:"The mission vessel assigned to humanity's first interstellar journey toward the Proxima Centauri system.",description:"Lumen is recorded here through confirmed public mission information only. Technical specifications not yet approved as canon are intentionally absent.",status:"public",canonStatus:"confirmed",tags:["vessel","interstellar","mission lumen"],metadata:{Classification:"Mission vessel",Mission:"Mission Lumen",Destination:"Proxima Centauri system"},relationships:[{targetId:"mission-lumen",type:"assigned to"},{targetId:"proxima-centauri",type:"destination"},{targetId:"gaia",type:"onboard system"}],lastReviewed:"2026-10-05"},
 {id:"gaia",slug:"gaia",title:"Gaia",type:"system",summary:"A major system associated with Lumen and Mission Lumen.",description:"The public archive acknowledges Gaia as a named mission system. Details beyond this classification await canon approval.",status:"public",canonStatus:"confirmed",tags:["system","lumen"],relationships:[{targetId:"lumen",type:"aboard"}],lastReviewed:"2026-10-05"},
 {id:"elena-carter",slug:"elena-carter",title:"Elena Carter",type:"person",summary:"A person associated with the public record of Mission Lumen.",description:"A fuller public biography has not yet been approved for publication.",status:"public",canonStatus:"confirmed",tags:["person","mission lumen"],relationships:[{targetId:"mission-lumen",type:"associated with"}],lastReviewed:"2026-10-05"},
 {id:"proxima-centauri",slug:"proxima-centauri",title:"Proxima Centauri",type:"celestial_body",summary:"The nearest known star to the Sun and the destination system of Mission Lumen.",description:"Proxima Centauri lies approximately 4.24 light-years from Earth. In the Proxima universe, this real astronomical neighbor defines the scale of humanity's first interstellar undertaking.",status:"public",canonStatus:"confirmed",tags:["star","destination","astronomy"],metadata:{Classification:"Red dwarf star",Distance:"Approximately 4.24 light-years",System:"Alpha Centauri"},relationships:[{targetId:"proxima-b",type:"orbited by"},{targetId:"mission-lumen",type:"destination of"}],lastReviewed:"2026-10-05"},
 {id:"proxima-b",slug:"proxima-b",title:"Proxima b",type:"celestial_body",summary:"An exoplanet orbiting Proxima Centauri.",description:"The public record is limited to the object's established astronomical identity. Story-dependent knowledge is excluded.",status:"public",canonStatus:"confirmed",tags:["exoplanet","astronomy","proxima"],relationships:[{targetId:"proxima-centauri",type:"orbits"}],lastReviewed:"2026-10-05"},
 {id:"fusion-drive",slug:"fusion-drive",title:"Fusion Drive",type:"technology",summary:"A propulsion technology associated with interstellar mission architecture.",description:"No unapproved performance figures or engineering details are published in this record.",status:"public",canonStatus:"confirmed",tags:["propulsion","fusion","technology"],relationships:[{targetId:"lumen",type:"associated vessel"}],lastReviewed:"2026-10-05"},
 {id:"mission-lumen",slug:"mission-lumen",title:"Mission Lumen",type:"mission",summary:"Humanity's first interstellar expedition toward the Proxima Centauri system.",description:"The archive documents the mission's public purpose, architecture and context. Outcomes and narrative events remain outside the public canon.",status:"public",canonStatus:"confirmed",tags:["mission","interstellar","proxima"],metadata:{Vessel:"Lumen",Destination:"Proxima Centauri system",Scope:"First interstellar expedition"},relationships:[{targetId:"lumen",type:"mission vessel"},{targetId:"proxima-centauri",type:"destination"},{targetId:"earth-departure-era",type:"historical context"}],lastReviewed:"2026-10-05"},
 {id:"interstellar-communication",slug:"interstellar-communication",title:"Interstellar Communication",type:"science",summary:"The exchange of information across interstellar distances and unavoidable light-speed delay.",description:"Communication over 4.24 light-years cannot be immediate. This constraint shapes the public scientific context of the mission without revealing story events.",status:"public",canonStatus:"confirmed",tags:["communication","light speed","science"],relationships:[{targetId:"mission-lumen",type:"mission context"}],lastReviewed:"2026-10-05"},
 {id:"closed-ecological-systems",slug:"closed-ecological-systems",title:"Closed Ecological Systems",type:"science",summary:"Life-support environments designed to recycle critical resources over long durations.",description:"Closed ecological systems are part of the scientific context for sustained human travel beyond Earth.",status:"public",canonStatus:"confirmed",tags:["ecology","life support","science"],relationships:[{targetId:"lumen",type:"mission context"}],lastReviewed:"2026-10-05"},
 {id:"earth-departure-era",slug:"earth-departure-era",title:"Earth Departure Era",type:"era",summary:"The historical period surrounding preparation for humanity's first interstellar mission.",description:"This record is reserved for approved public context. Specific dates remain unpublished until canon review is complete.",status:"public",canonStatus:"confirmed",tags:["history","earth","timeline"],relationships:[{targetId:"mission-lumen",type:"contains"}],lastReviewed:"2026-10-05"},
 {id:"proxima-journey",slug:"proxima-journey",title:"Proxima Journey",type:"book",summary:"The current working title of the book series set in the Proxima universe.",description:"The books are one path into the universe. Their narrative events are deliberately separate from this public knowledge archive.",status:"public",canonStatus:"confirmed",tags:["books","series"],lastReviewed:"2026-10-05"},
 {id:"restricted-anomaly",slug:"restricted-anomaly",title:"Restricted Anomaly",type:"science",summary:"Internal only.",status:"plot_locked",canonStatus:"provisional",tags:["restricted"],lastReviewed:"2026-10-05"}
];
