import Link from "next/link";
import { SiteShell } from "@/components/site-shell";

const portals = [["01","People","Public personnel records and biographies"],["02","Technology","Systems that make the journey possible"],["03","Science","The physical ideas beneath the universe"],["04","Places","Worlds, systems and points of origin"],["05","Missions","Programs, vessels and public objectives"],["06","Timeline","Context before the interstellar era"]];
const records = [["LUMEN-001","Lumen","Vessel"],["SYS-GAIA-001","Gaia","System"],["AST-PC-001","Proxima Centauri","Celestial body"],["MIS-LUMEN-001","Mission Lumen","Mission"]];

export default function Home() {
  return <SiteShell><main>
    <section className="hero" aria-labelledby="hero-title"><div className="star-field" aria-hidden="true"/><div className="hero-orbit orbit-a"/><div className="hero-orbit orbit-b"/>
      <div className="hero-copy page-grid"><div className="hero-kicker mono">A fictional universe / public canon</div><h1 id="hero-title">The distance<br/>between worlds.</h1><p className="hero-intro">Humanity&apos;s first interstellar journey begins with a question measured across 4.24 light-years.</p><Link href="/universe" className="text-link">Enter the universe <span>↗</span></Link></div>
      <div className="hero-measure mono" aria-label="Distance from Sol to Proxima Centauri: 4.24 light-years"><span>SOL</span><span className="measure-line"/><span>4.24 LY</span><span className="measure-line"/><span>PROXIMA</span></div><div className="hero-coordinates mono">REF / HELIOCENTRIC<br/>RANGE / INTERSTELLAR</div>
    </section>
    <section className="journey section page-grid"><div className="section-index mono">01 / THE JOURNEY</div><div className="section-body"><p className="eyebrow">Mission Lumen</p><h2>A departure from the only world we have known.</h2><p className="lede">Lumen is the mission vessel at the center of humanity&apos;s first attempt to reach the Proxima Centauri system. This archive records the public knowledge surrounding that undertaking.</p><div className="route-diagram" aria-label="Journey from Earth through deep space to Proxima Centauri"><div className="route-node"><b>Earth</b><span>Origin</span></div><div className="route-track"><i/><span className="mono">4.24 LIGHT-YEARS</span></div><div className="route-node align-right"><b>Proxima Centauri</b><span>Destination system</span></div></div></div></section>
    <section className="lumen section page-grid"><div className="section-index mono">02 / THE VESSEL</div><div className="section-body split"><div><p className="eyebrow">Record / LUMEN-001</p><h2>Lumen</h2><p className="lede">An interstellar mission vessel bound for the Proxima Centauri system.</p><Link href="/records/lumen" className="text-link">Open vessel record <span>↗</span></Link></div><dl className="data-list"><div><dt>Classification</dt><dd>Mission vessel</dd></div><div><dt>Mission</dt><dd>Mission Lumen</dd></div><div><dt>Destination</dt><dd>Proxima system</dd></div><div><dt>Record state</dt><dd>Public / confirmed</dd></div></dl></div></section>
    <section className="universe section"><div className="page-grid"><div className="section-index mono">03 / EXPLORE</div><div className="section-body"><p className="eyebrow">The universe</p><h2>Every record exists in relation to another.</h2></div></div><div className="portal-grid">{portals.map(([i,t,d])=><Link href={t==="Timeline"?"/timeline":`/universe?type=${t.toLowerCase()}`} className="portal" key={t}><span className="mono">{i}</span><h3>{t}</h3><p>{d}</p><i>↗</i></Link>)}</div></section>
    <section className="science section page-grid"><div className="section-index mono">04 / SCIENCE</div><div className="section-body split"><div><p className="eyebrow">Known constraints</p><h2>Wonder, bounded by physics.</h2></div><div><p className="lede small">The universe of Proxima treats distance, time, energy and survival as constraints—not scenery.</p><div className="topic-row mono"><span>RELATIVITY</span><span>PROPULSION</span><span>ECOLOGY</span><span>COMMUNICATION</span></div></div></div></section>
    <section className="records section page-grid"><div className="section-index mono">05 / PUBLIC RECORDS</div><div className="section-body"><div className="section-heading"><div><p className="eyebrow">Archive selection</p><h2>Open records</h2></div><Link href="/archive" className="text-link">View archive <span>↗</span></Link></div><div className="record-list">{records.map(([id,title,type])=><Link href={`/records/${title.toLowerCase().replaceAll(" ","-")}`} key={id}><span className="mono">{id}</span><b>{title}</b><em>{type}</em><i>↗</i></Link>)}</div></div></section>
    <section className="books section page-grid"><div className="section-index mono">06 / THE BOOKS</div><div className="section-body split"><div><p className="eyebrow">A gateway into the universe</p><h2><em>Proxima Journey</em></h2></div><div><p className="lede small">The working title of the series set within this universe. Story knowledge remains beyond the public archive.</p><Link href="/books" className="text-link">About the books <span>↗</span></Link></div></div></section>
  </main></SiteShell>;
}
